apiVersion: cert-manager.io/v1
# ClusterIssuer vs Issuer
# The difference is just that the ClusterIssuer can issue certificates for any namespace
# This is just what we need, we're not THAT big ;-)
kind: ClusterIssuer
metadata:
  name: letsencrypt-http01-issuer
spec:
  acme:
    privateKeySecretRef:
      name: letsencrypt
# Specify an email address here
#   email: <your.email@example.com>
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
       ingress:
         class: kourier.ingress.networking.knative.dev # We're using kourier, not istio, so specify that here